#!bin/bash
mv /Users/kristen/Development/nlp_project/forums/memory_loss/post_8229151.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/memory_loss/post_8296587.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/memory_loss/post_8408367.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/memory_loss/post_8271468.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/

mv /Users/kristen/Development/nlp_project/forums/memory_loss/post_2292345.txt /Users/kristen/Development/nlp_project/forums_v2/both/

mv /Users/kristen/Development/nlp_project/forums/caregivers/post_5625635.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/caregivers/post_3118159.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/caregivers/post_8286671.txt /Users/kristen/Development/nlp_project/forums_v2/alz/

mv /Users/kristen/Development/nlp_project/forums/caregivers/post_2575681.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/caregivers/post_4427982.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/caregivers/post_2746679.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/caregivers/post_6081429.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/caregivers/post_8289159.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/caregivers/post_6200763.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/caregivers/post_8384189.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/caregivers/post_5442472.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/caregivers/post_5463721.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/caregivers/post_5476480.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/caregivers/post_6488222.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/

mv /Users/kristen/Development/nlp_project/forums/caregivers/post_4451228.txt /Users/kristen/Development/nlp_project/forums_v2/both/

mv /Users/kristen/Development/nlp_project/forums/genetics/post_4814612.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/genetics/post_7013629.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/genetics/post_6274384.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/genetics/post_6274384.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/genetics/post_6274393.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/genetics/post_6274393.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/genetics/post_5172780.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/genetics/post_6488240.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/genetics/post_5454775.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/genetics/post_6669353.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/genetics/post_6669353.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/genetics/post_4579040.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/genetics/post_6082745.txt /Users/kristen/Development/nlp_project/forums_v2/alz/

mv /Users/kristen/Development/nlp_project/forums/genetics/post_3309133.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/genetics/post_6972484.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/

mv /Users/kristen/Development/nlp_project/forums/dementia/post_3087870.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_5399047.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_3195838.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_6026102.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_6824323.txt /Users/kristen/Development/nlp_project/forums_v2/both/

mv /Users/kristen/Development/nlp_project/forums/alz/post_4782257.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5949974.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3526762.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4792524.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3599101.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6034607.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2081694.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2143067.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4886015.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7363820.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7391327.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3735783.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7409910.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6230231.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6258936.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7522506.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6258940.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2512815.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7642072.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4062902.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4091291.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4142190.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5274780.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5274780.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7860509.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4439149.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4446257.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5457700.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5654284.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3223348.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_8241681.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4540286.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_8260335.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3271813.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3314967.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6935010.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3332191.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5862970.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3389045.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5912553.txt /Users/kristen/Development/nlp_project/forums_v2/both/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3492486.txt /Users/kristen/Development/nlp_project/forums_v2/both/

mv /Users/kristen/Development/nlp_project/forums/alz/post_3890635.txt /Users/kristen/Development/nlp_project/forums_v2/alz/

mv /Users/kristen/Development/nlp_project/forums/dementia/post_2765497.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_3949051.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_4842372.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_2824268.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_4070994.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_5044647.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_7330416.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_2925037.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_4072713.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_5367452.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_7459857.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_1980573.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_4096035.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_7867311.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_2058641.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_2058641.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_4432154.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_5775087.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_8238664.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_3468678.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_5959764.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_3494708.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_8660432.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_2187465.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_3509643.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_4535207.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_6357072.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_8677951.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_3615321.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_4559388.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_6699527.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_8678875.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_2408215.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_4726151.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_6740813.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_8717520.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_8717520.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_2739879.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_3931075.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_4730888.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/


mv /Users/kristen/Development/nlp_project/forums/dementia/post_2765497.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_3949051.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_4842372.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_2824268.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_4070994.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_5044647.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_7330416.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_2925037.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_4072713.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_5367452.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_7459857.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_1980573.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_4096035.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_7867311.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_2058641.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_2058641.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_4432154.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_5775087.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_8238664.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_3468678.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_5959764.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_3494708.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_8660432.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_2187465.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_3509643.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_4535207.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_6357072.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_8677951.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_3615321.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_4559388.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_6699527.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_8678875.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_2408215.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_4726151.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_6740813.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_8717520.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_8717520.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_2739879.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_3931075.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/dementia/post_4730888.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/

mv /Users/kristen/Development/nlp_project/forums/dementia/post_3890635.txt /Users/kristen/Development/nlp_project/forums_v2/alz/

mv /Users/kristen/Development/nlp_project/forums/alz/post_3518372.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7190828.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7190828.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_1995614.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3529142.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4795280.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7213353.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3550501.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3550501.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4795347.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5993924.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7229137.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2049425.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3594398.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4857580.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4861406.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4873436.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4873436.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4874866.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7291951.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2210910.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3684971.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4890065.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4890389.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6127540.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2234892.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2234892.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4917755.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4917755.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2262174.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2283299.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3717718.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2291884.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2291884.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3785064.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2332406.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2332406.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3838867.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2357972.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2357972.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3838981.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3838981.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5058816.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6254507.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2373497.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3853624.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5071761.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5071761.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6257817.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6257817.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3898999.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5100342.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3900423.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3900423.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3928036.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5133930.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6258942.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3938984.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3938984.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5138276.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5138276.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6261652.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3947145.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5150097.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6312255.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3973445.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5151919.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5151919.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6327011.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6327011.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7576021.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2542770.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5160266.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6332561.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2544179.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2544179.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5166101.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5169258.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7603881.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7603881.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2625193.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4003311.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5171871.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5171871.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5171871.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6353656.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7605114.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2649129.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4024357.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5172421.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5172421.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6370454.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2670291.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2670291.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5174174.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5174174.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2675470.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2675470.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6431946.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6431946.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7651184.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4086214.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5183502.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7661362.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6570328.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2924232.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4100216.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5230265.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5230265.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6574903.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6574903.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7699043.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7699043.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6578463.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7722627.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3015367.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3035587.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4372887.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5333076.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3078259.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4390048.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7862789.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3078568.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7887644.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3095226.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7947654.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3106812.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4478669.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5514082.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3178102.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6823128.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3243872.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3243872.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4517648.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3249282.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_8255177.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6863772.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4558082.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_8405796.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6928869.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4601353.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4625162.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6958844.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3382176.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3382176.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4646770.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5874970.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5874970.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_8596057.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_8596057.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_8596057.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4662462.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5883872.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5883872.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_8596101.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4672309.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_8630027.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7096158.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7096158.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_8637932.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3463088.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4697264.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7147496.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4735139.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5914238.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7147517.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4747883.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4747883.txt /Users/kristen/Development/nlp_project/forums_v2/alz/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4776178.txt /Users/kristen/Development/nlp_project/forums_v2/alz/

mv /Users/kristen/Development/nlp_project/forums/alz/post_7188799.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5984882.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7198650.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3534570.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7252205.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7276697.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3671474.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6191442.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2331582.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7452928.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2415369.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7531344.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7566390.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_2530989.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4002394.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4041467.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6422925.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6478460.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3022943.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5284201.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6629578.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6711521.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3113185.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5537462.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6806525.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_8114011.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3193443.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5695673.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3252346.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5764690.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6868382.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_8326467.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_4558172.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_8408364.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_8408364.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6941163.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3361739.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_6941873.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3361933.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_8594360.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7021932.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_5886066.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3429358.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_8683622.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_3464098.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
mv /Users/kristen/Development/nlp_project/forums/alz/post_7162344.txt /Users/kristen/Development/nlp_project/forums_v2/dementia/
